# Generated by Django 4.2.2 on 2023-06-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='Eposta Adresi'),
        ),
    ]
