# Generated by Django 4.2.2 on 2023-06-15 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursesmodel_options'),
        ('account', '0004_customusermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'Üye Profil Linki',
                'verbose_name_plural': 'Üye Profil Linkleri',
                'db_table': 'users_links',
            },
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='linkedin_link',
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_users', to='courses.coursesmodel')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_users', to='courses.periodmodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customusermodel',
            name='social_links',
            field=models.ManyToManyField(blank=True, related_name='social_links', to='account.userlinksmodel'),
        ),
    ]
