# Generated by Django 4.2.2 on 2023-06-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_studentmodel_options_rolesmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instructormodel',
            options={'verbose_name': 'Eğitmen', 'verbose_name_plural': 'Eğitmenler'},
        ),
        migrations.AlterModelTable(
            name='instructormodel',
            table='instructors',
        ),
    ]
