# Generated by Django 4.2.2 on 2023-06-15 19:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursesmodel_options'),
        ('account', '0007_alter_instructormodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_users', to='courses.coursesmodel', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='period_users', to='courses.periodmodel', verbose_name='Dönem'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_no',
            field=models.CharField(blank=True, unique=True, verbose_name='Öğrenci Numarası'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Üye'),
        ),
    ]
