# Generated by Django 4.2.2 on 2023-06-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_studentmodel_course_alter_studentmodel_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_no',
            field=models.CharField(blank=True, max_length=11, unique=True, verbose_name='Öğrenci Numarası'),
        ),
    ]
