# Generated by Django 4.2.2 on 2023-06-15 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_coursesmodel_options'),
        ('account', '0009_alter_studentmodel_student_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ayrılış Tarihi'),
        ),
        migrations.AddField(
            model_name='instructormodel',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name='Başlangıç Tarihi'),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.coursesmodel', verbose_name='Bağlı Olduğu Kurslar'),
        ),
        migrations.AlterField(
            model_name='instructormodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Üye'),
        ),
    ]
