# Generated by Django 4.2.2 on 2023-06-15 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_instructormodel_end_date_instructormodel_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructormodel',
            name='is_leave',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='StaffModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('start_date', models.DateTimeField(null=True, verbose_name='Başlangıç Tarihi')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Ayrılış Tarihi')),
                ('is_leave', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Üye')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
