# Generated by Django 4.2.2 on 2023-06-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_instructormodel_is_leave_staffmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Personel Departmanı',
                'verbose_name_plural': 'Personel Departmanları',
                'db_table': 'staff_departments',
            },
        ),
        migrations.AlterModelOptions(
            name='staffmodel',
            options={'verbose_name': 'Personel', 'verbose_name_plural': 'Personeller'},
        ),
        migrations.AlterModelTable(
            name='staffmodel',
            table='staffs',
        ),
        migrations.AddField(
            model_name='staffmodel',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='account.staffdepartmentmodel', verbose_name='Departmanı'),
        ),
    ]
