# Generated by Django 4.2.2 on 2023-06-12 16:57

import apps.videos.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocommentmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.videomodel', validators=[apps.videos.validators.validate_file_extension]),
        ),
    ]
