# Generated by Django 4.2.2 on 2023-06-12 16:58

import apps.videos.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videocommentmodel_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomodel',
            name='video',
        ),
        migrations.AddField(
            model_name='videomodel',
            name='video_file',
            field=models.FileField(null=True, upload_to='videos/', validators=[apps.videos.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='videocommentmodel',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.videomodel'),
        ),
    ]
