# Generated by Django 4.2.2 on 2023-06-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_alter_videomodel_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocommentmodel',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='videocommentmodel',
            name='updated_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
