# Generated by Django 4.2.2 on 2023-06-13 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_videocommentmodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videocommentmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videos.videocommentmodel'),
        ),
    ]
