# Generated by Django 4.2.2 on 2023-06-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursesmodel',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
    ]
