# Generated by Django 4.2.2 on 2023-06-14 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('link', models.URLField(max_length=180)),
                ('language', models.CharField(choices=[('tr', 'Türkçe'), ('en', 'İngilizce')], max_length=4)),
                ('created_on', models.DateTimeField(editable=False)),
                ('updated_on', models.DateTimeField(editable=False)),
                ('author', models.ForeignKey(limit_choices_to={'groups': 2}, on_delete=django.db.models.deletion.CASCADE, related_name='links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Faydalı Link',
                'verbose_name_plural': 'Faydalı Linkler',
                'db_table': 'useful_links',
            },
        ),
    ]
