# Generated by Django 4.2.2 on 2023-06-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useful_links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usefullinksmodel',
            name='created_on',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='usefullinksmodel',
            name='updated_on',
            field=models.DateTimeField(editable=False),
        ),
    ]
